//
//  ProgressMeterStyleKit.h
//  ProgressMeter
//
//  Created by Serko on 28/11/2014.
//  Copyright (c) 2014 HavasLynx. All rights reserved.
//
//  Generated by PaintCode (www.paintcodeapp.com)
//

#import <Foundation/Foundation.h>
#import <UIKit/UIKit.h>


@interface ProgressMeterStyleKit : NSObject

// Colors
+ (UIColor*)progressColor0;
+ (UIColor*)progressColor1;
+ (UIColor*)progressColor2;
+ (UIColor*)progressColor3;
+ (UIColor*)progressColor4;
+ (UIColor*)progressColor5;
+ (UIColor*)progressColor6;
+ (UIColor*)progressColor7;
+ (UIColor*)progressColor8;
+ (UIColor*)progressColor9;
+ (UIColor*)progressColor10;
+ (UIColor*)progressColor11;
+ (UIColor*)progressColor12;
+ (UIColor*)progressColor13;
+ (UIColor*)progressColor14;
+ (UIColor*)progressColor15;

// Drawing Methods
+ (void)drawCanvas1;

@end
