//
//  ProgressMeterStyleKit.m
//  ProgressMeter
//
//  Created by Serko on 28/11/2014.
//  Copyright (c) 2014 HavasLynx. All rights reserved.
//
//  Generated by PaintCode (www.paintcodeapp.com)
//

#import "ProgressMeterStyleKit.h"


@implementation ProgressMeterStyleKit

#pragma mark Cache

static UIColor* _progressColor0 = nil;
static UIColor* _progressColor1 = nil;
static UIColor* _progressColor2 = nil;
static UIColor* _progressColor3 = nil;
static UIColor* _progressColor4 = nil;
static UIColor* _progressColor5 = nil;
static UIColor* _progressColor6 = nil;
static UIColor* _progressColor7 = nil;
static UIColor* _progressColor8 = nil;
static UIColor* _progressColor9 = nil;
static UIColor* _progressColor10 = nil;
static UIColor* _progressColor11 = nil;
static UIColor* _progressColor12 = nil;
static UIColor* _progressColor13 = nil;
static UIColor* _progressColor14 = nil;
static UIColor* _progressColor15 = nil;

#pragma mark Initialization

+ (void)initialize
{
    // Colors Initialization
    _progressColor0 = [UIColor colorWithRed: 0.91 green: 0.278 blue: 0.137 alpha: 1];
    _progressColor1 = [UIColor colorWithRed: 0.91 green: 0.286 blue: 0.118 alpha: 1];
    _progressColor2 = [UIColor colorWithRed: 0.914 green: 0.325 blue: 0.122 alpha: 1];
    _progressColor3 = [UIColor colorWithRed: 0.914 green: 0.361 blue: 0.118 alpha: 1];
    _progressColor4 = [UIColor colorWithRed: 0.953 green: 0.569 blue: 0.125 alpha: 1];
    _progressColor5 = [UIColor colorWithRed: 0.973 green: 0.682 blue: 0.059 alpha: 1];
    _progressColor6 = [UIColor colorWithRed: 0.992 green: 0.855 blue: 0 alpha: 1];
    _progressColor7 = [UIColor colorWithRed: 0.976 green: 0.882 blue: 0.016 alpha: 1];
    _progressColor8 = [UIColor colorWithRed: 0.941 green: 0.898 blue: 0.047 alpha: 1];
    _progressColor9 = [UIColor colorWithRed: 0.902 green: 0.878 blue: 0.027 alpha: 1];
    _progressColor10 = [UIColor colorWithRed: 0.663 green: 0.784 blue: 0.09 alpha: 1];
    _progressColor11 = [UIColor colorWithRed: 0.486 green: 0.725 blue: 0.165 alpha: 1];
    _progressColor12 = [UIColor colorWithRed: 0.404 green: 0.706 blue: 0.192 alpha: 1];
    _progressColor13 = [UIColor colorWithRed: 0.392 green: 0.702 blue: 0.192 alpha: 1];
    _progressColor14 = [UIColor colorWithRed: 0.404 green: 0.706 blue: 0.192 alpha: 1];
    _progressColor15 = [UIColor colorWithRed: 0.408 green: 0.706 blue: 0.192 alpha: 1];

}

#pragma mark Colors

+ (UIColor*)progressColor0 { return _progressColor0; }
+ (UIColor*)progressColor1 { return _progressColor1; }
+ (UIColor*)progressColor2 { return _progressColor2; }
+ (UIColor*)progressColor3 { return _progressColor3; }
+ (UIColor*)progressColor4 { return _progressColor4; }
+ (UIColor*)progressColor5 { return _progressColor5; }
+ (UIColor*)progressColor6 { return _progressColor6; }
+ (UIColor*)progressColor7 { return _progressColor7; }
+ (UIColor*)progressColor8 { return _progressColor8; }
+ (UIColor*)progressColor9 { return _progressColor9; }
+ (UIColor*)progressColor10 { return _progressColor10; }
+ (UIColor*)progressColor11 { return _progressColor11; }
+ (UIColor*)progressColor12 { return _progressColor12; }
+ (UIColor*)progressColor13 { return _progressColor13; }
+ (UIColor*)progressColor14 { return _progressColor14; }
+ (UIColor*)progressColor15 { return _progressColor15; }

#pragma mark Drawing Methods

+ (void)drawCanvas1
{
}

@end
